apiVersion: v1
kind: Service
metadata:
  name: git-node-service
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: git-node
  ports:
    - name: http
      port: 8080
      targetPort: 3000
      protocol: TCP
